# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dust3r/proto/common/calibration.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'dust3r/proto/common/calibration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dust3r.proto.common import geometry_pb2 as dust3r_dot_proto_dot_common_dot_geometry__pb2
from dust3r.proto.common import ids_pb2 as dust3r_dot_proto_dot_common_dot_ids__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%dust3r/proto/common/calibration.proto\x12\x13\x63ovariant.brain_api\x1a\"dust3r/proto/common/geometry.proto\x1a\x1d\x64ust3r/proto/common/ids.proto\"P\n\x13IntrinsicParameters\x12\n\n\x02\x66x\x18\x01 \x01(\x02\x12\n\n\x02\x66y\x18\x02 \x01(\x02\x12\n\n\x02px\x18\x03 \x01(\x02\x12\n\n\x02py\x18\x04 \x01(\x02\x12\t\n\x01s\x18\x05 \x01(\x02\"\\\n\x1e\x46iveCoeffsDistortionParameters\x12\n\n\x02k1\x18\x01 \x01(\x02\x12\n\n\x02k2\x18\x02 \x01(\x02\x12\n\n\x02p1\x18\x03 \x01(\x02\x12\n\n\x02p2\x18\x04 \x01(\x02\x12\n\n\x02k3\x18\x05 \x01(\x02\"\x91\x01\n\x14\x44istortionParameters\x12`\n!five_coeffs_distortion_parameters\x18\x01 \x01(\x0b\x32\x33.covariant.brain_api.FiveCoeffsDistortionParametersH\x00\x42\x17\n\x15\x64istortion_parameters\"F\n\x0f\x43\x61meraExtrinsic\x12\x33\n\ttransform\x18\x01 \x01(\x0b\x32 .covariant.brain_api.Transform3D\"\xde\x01\n\x0f\x43\x61meraIntrinsic\x12\x30\n\tcamera_id\x18\x01 \x01(\x0b\x32\x1d.covariant.brain_api.CameraID\x12;\n\tintrinsic\x18\x02 \x01(\x0b\x32(.covariant.brain_api.IntrinsicParameters\x12=\n\ndistortion\x18\x03 \x01(\x0b\x32).covariant.brain_api.DistortionParameters\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\r\n\x05width\x18\x05 \x01(\x05\"\xcd\x01\n\x1e\x43\x61meraRigCalibrationParameters\x12\x37\n\rcamera_rig_id\x18\x01 \x01(\x0b\x32 .covariant.brain_api.CameraRigID\x12\x38\n\nintrinsics\x18\x02 \x03(\x0b\x32$.covariant.brain_api.CameraIntrinsic\x12\x38\n\nextrinsics\x18\x03 \x03(\x0b\x32$.covariant.brain_api.CameraExtrinsicb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dust3r.proto.common.calibration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTRINSICPARAMETERS']._serialized_start=129
  _globals['_INTRINSICPARAMETERS']._serialized_end=209
  _globals['_FIVECOEFFSDISTORTIONPARAMETERS']._serialized_start=211
  _globals['_FIVECOEFFSDISTORTIONPARAMETERS']._serialized_end=303
  _globals['_DISTORTIONPARAMETERS']._serialized_start=306
  _globals['_DISTORTIONPARAMETERS']._serialized_end=451
  _globals['_CAMERAEXTRINSIC']._serialized_start=453
  _globals['_CAMERAEXTRINSIC']._serialized_end=523
  _globals['_CAMERAINTRINSIC']._serialized_start=526
  _globals['_CAMERAINTRINSIC']._serialized_end=748
  _globals['_CAMERARIGCALIBRATIONPARAMETERS']._serialized_start=751
  _globals['_CAMERARIGCALIBRATIONPARAMETERS']._serialized_end=956
# @@protoc_insertion_point(module_scope)
