# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dust3r/proto/common/camera.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'dust3r/proto/common/camera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dust3r.proto.common import calibration_pb2 as dust3r_dot_proto_dot_common_dot_calibration__pb2
from dust3r.proto.common import ids_pb2 as dust3r_dot_proto_dot_common_dot_ids__pb2
from dust3r.proto.common import image_pb2 as dust3r_dot_proto_dot_common_dot_image__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n dust3r/proto/common/camera.proto\x12\x13\x63ovariant.brain_api\x1a%dust3r/proto/common/calibration.proto\x1a\x1d\x64ust3r/proto/common/ids.proto\x1a\x1f\x64ust3r/proto/common/image.proto\"\xe7\x01\n\x0b\x43\x61meraImage\x12\x30\n\tcamera_id\x18\x01 \x01(\x0b\x32\x1d.covariant.brain_api.CameraID\x12)\n\x05image\x18\x02 \x01(\x0b\x32\x1a.covariant.brain_api.Image\x12<\n\nintrinsics\x18\x03 \x01(\x0b\x32(.covariant.brain_api.IntrinsicParameters\x12=\n\ndistortion\x18\x04 \x01(\x0b\x32).covariant.brain_api.DistortionParametersb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dust3r.proto.common.camera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMERAIMAGE']._serialized_start=161
  _globals['_CAMERAIMAGE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
