# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dust3r/proto/common/frame.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'dust3r/proto/common/frame.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dust3r.proto.common import ids_pb2 as dust3r_dot_proto_dot_common_dot_ids__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x64ust3r/proto/common/frame.proto\x12\x13\x63ovariant.brain_api\x1a\x1d\x64ust3r/proto/common/ids.proto\"I\n\x07\x46rameID\x12\x32\n\tcamera_id\x18\x01 \x01(\x0b\x32\x1d.covariant.brain_api.CameraIDH\x00\x42\n\n\x08\x66rame_id\"_\n\x05\x46rame\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.covariant.brain_api.FrameType\x12(\n\x02id\x18\x02 \x01(\x0b\x32\x1c.covariant.brain_api.FrameID*\xb1\x02\n\tFrameType\x12\x1a\n\x16\x46RAME_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11\x46RAME_TYPE_CAMERA\x10\x01\x12\x19\n\x15\x46RAME_TYPE_ROBOT_BASE\x10\x02\x12\x18\n\x14\x46RAME_TYPE_GRASP_TCP\x10\x03\x12\x1c\n\x18\x46RAME_TYPE_TARGET_OBJECT\x10\x04\x12!\n\x1d\x46RAME_TYPE_GRASPED_OBJECT_TOP\x10\x05\x12$\n FRAME_TYPE_GRASPED_OBJECT_CENTER\x10\x06\x12$\n FRAME_TYPE_GRASPED_OBJECT_BOTTOM\x10\x07\x12\x19\n\x15\x46RAME_TYPE_ROBOT_TOOL\x10\x08\x12\x14\n\x10\x46RAME_TYPE_WORLD\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dust3r.proto.common.frame_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMETYPE']._serialized_start=260
  _globals['_FRAMETYPE']._serialized_end=565
  _globals['_FRAMEID']._serialized_start=87
  _globals['_FRAMEID']._serialized_end=160
  _globals['_FRAME']._serialized_start=162
  _globals['_FRAME']._serialized_end=257
# @@protoc_insertion_point(module_scope)
