# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dust3r/proto/common/geometry.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'dust3r/proto/common/geometry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dust3r.proto.common import frame_pb2 as dust3r_dot_proto_dot_common_dot_frame__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"dust3r/proto/common/geometry.proto\x12\x13\x63ovariant.brain_api\x1a\x1f\x64ust3r/proto/common/frame.proto\"/\n\x0c\x43oordinate3D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\".\n\x0b\x44imension3D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"<\n\x0eUnitQuaternion\x12\t\n\x01w\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\"u\n\x04Pose\x12\x33\n\x08position\x18\x01 \x01(\x0b\x32!.covariant.brain_api.Coordinate3D\x12\x38\n\x0borientation\x18\x02 \x01(\x0b\x32#.covariant.brain_api.UnitQuaternion\"\x94\x01\n\x0bTransform3D\x12\'\n\x04pose\x18\x01 \x01(\x0b\x32\x19.covariant.brain_api.Pose\x12.\n\nfrom_frame\x18\x02 \x01(\x0b\x32\x1a.covariant.brain_api.Frame\x12,\n\x08to_frame\x18\x03 \x01(\x0b\x32\x1a.covariant.brain_api.Frameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dust3r.proto.common.geometry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COORDINATE3D']._serialized_start=92
  _globals['_COORDINATE3D']._serialized_end=139
  _globals['_DIMENSION3D']._serialized_start=141
  _globals['_DIMENSION3D']._serialized_end=187
  _globals['_UNITQUATERNION']._serialized_start=189
  _globals['_UNITQUATERNION']._serialized_end=249
  _globals['_POSE']._serialized_start=251
  _globals['_POSE']._serialized_end=368
  _globals['_TRANSFORM3D']._serialized_start=371
  _globals['_TRANSFORM3D']._serialized_end=519
# @@protoc_insertion_point(module_scope)
