# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dust3r/proto/common/ids.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'dust3r/proto/common/ids.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x64ust3r/proto/common/ids.proto\x12\x13\x63ovariant.brain_api\"\x16\n\x08\x43\x61meraID\x12\n\n\x02id\x18\x01 \x01(\t\"\x19\n\x0b\x43\x61meraRigID\x12\n\n\x02id\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dust3r.proto.common.ids_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMERAID']._serialized_start=54
  _globals['_CAMERAID']._serialized_end=76
  _globals['_CAMERARIGID']._serialized_start=78
  _globals['_CAMERARIGID']._serialized_end=103
# @@protoc_insertion_point(module_scope)
