# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dust3r/proto/common/image.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'dust3r/proto/common/image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x64ust3r/proto/common/image.proto\x12\x13\x63ovariant.brain_api\"\\\n\x10RegionOfInterest\x12\x0f\n\x07min_row\x18\x01 \x01(\x05\x12\x12\n\nmin_column\x18\x02 \x01(\x05\x12\x0f\n\x07max_row\x18\x03 \x01(\x05\x12\x12\n\nmax_column\x18\x04 \x01(\x05\"3\n\nDepthRange\x12\x12\n\nnear_plane\x18\x01 \x01(\x02\x12\x11\n\tfar_plane\x18\x02 \x01(\x02\"\x99\x02\n\rImageMetadata\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12;\n\x0c\x63hannel_type\x18\x03 \x01(\x0e\x32%.covariant.brain_api.ImageChannelType\x12\x39\n\x0b\x64\x61ta_layout\x18\x04 \x01(\x0e\x32$.covariant.brain_api.ImageDataLayout\x12\x35\n\tdata_type\x18\x05 \x01(\x0e\x32\".covariant.brain_api.ImageDataType\x12:\n\x0b\x63ompression\x18\x06 \x01(\x0e\x32%.covariant.brain_api.ImageCompression\"p\n\x13ImageEncoderOptions\x12\x0e\n\x06height\x18\x01 \x01(\r\x12\r\n\x05width\x18\x02 \x01(\r\x12:\n\x0b\x63ompression\x18\x03 \x01(\x0e\x32%.covariant.brain_api.ImageCompression\"O\n\x05Image\x12\x34\n\x08metadata\x18\x01 \x01(\x0b\x32\".covariant.brain_api.ImageMetadata\x12\x10\n\x08raw_data\x18\x02 \x01(\x0c*u\n\x10ImageChannelType\x12\"\n\x1eIMAGE_CHANNEL_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n\x16IMAGE_CHANNEL_TYPE_RGB\x10\x01\x12!\n\x1dIMAGE_CHANNEL_TYPE_MONOCHROME\x10\x02*i\n\x0fImageDataLayout\x12!\n\x1dIMAGE_DATA_LAYOUT_UNSPECIFIED\x10\x00\x12\x19\n\x15IMAGE_DATA_LAYOUT_HWC\x10\x01\x12\x18\n\x14IMAGE_DATA_LAYOUT_HW\x10\x02*\x84\x01\n\rImageDataType\x12\x1f\n\x1bIMAGE_DATA_TYPE_UNSPECIFIED\x10\x00\x12\x19\n\x15IMAGE_DATA_TYPE_UINT8\x10\x01\x12\x1a\n\x16IMAGE_DATA_TYPE_UINT16\x10\x02\x12\x1b\n\x17IMAGE_DATA_TYPE_FLOAT32\x10\x03*\x87\x01\n\x10ImageCompression\x12!\n\x1dIMAGE_COMPRESSION_UNSPECIFIED\x10\x00\x12\x19\n\x15IMAGE_COMPRESSION_RAW\x10\x01\x12\x19\n\x15IMAGE_COMPRESSION_PNG\x10\x02\x12\x1a\n\x16IMAGE_COMPRESSION_JPEG\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dust3r.proto.common.image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGECHANNELTYPE']._serialized_start=682
  _globals['_IMAGECHANNELTYPE']._serialized_end=799
  _globals['_IMAGEDATALAYOUT']._serialized_start=801
  _globals['_IMAGEDATALAYOUT']._serialized_end=906
  _globals['_IMAGEDATATYPE']._serialized_start=909
  _globals['_IMAGEDATATYPE']._serialized_end=1041
  _globals['_IMAGECOMPRESSION']._serialized_start=1044
  _globals['_IMAGECOMPRESSION']._serialized_end=1179
  _globals['_REGIONOFINTEREST']._serialized_start=56
  _globals['_REGIONOFINTEREST']._serialized_end=148
  _globals['_DEPTHRANGE']._serialized_start=150
  _globals['_DEPTHRANGE']._serialized_end=201
  _globals['_IMAGEMETADATA']._serialized_start=204
  _globals['_IMAGEMETADATA']._serialized_end=485
  _globals['_IMAGEENCODEROPTIONS']._serialized_start=487
  _globals['_IMAGEENCODEROPTIONS']._serialized_end=599
  _globals['_IMAGE']._serialized_start=601
  _globals['_IMAGE']._serialized_end=680
# @@protoc_insertion_point(module_scope)
