# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dust3r.proto.inference import predict_depth_with_dust3r_pb2 as dust3r_dot_proto_dot_inference_dot_predict__depth__with__dust3r__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dust3r/proto/inference/predict_depth_with_dust3r_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Dust3rInferenceServiceStub(object):
    """Service for running Dust3r depth inference
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictDepth = channel.unary_unary(
                '/covariant.brain_api.Dust3rInferenceService/PredictDepth',
                request_serializer=dust3r_dot_proto_dot_inference_dot_predict__depth__with__dust3r__pb2.PredictDust3rDepthRequest.SerializeToString,
                response_deserializer=dust3r_dot_proto_dot_inference_dot_predict__depth__with__dust3r__pb2.PredictDust3rDepthResponse.FromString,
                _registered_method=True)


class Dust3rInferenceServiceServicer(object):
    """Service for running Dust3r depth inference
    """

    def PredictDepth(self, request, context):
        """Predicts depth maps from a set of captured images
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Dust3rInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictDepth': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictDepth,
                    request_deserializer=dust3r_dot_proto_dot_inference_dot_predict__depth__with__dust3r__pb2.PredictDust3rDepthRequest.FromString,
                    response_serializer=dust3r_dot_proto_dot_inference_dot_predict__depth__with__dust3r__pb2.PredictDust3rDepthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'covariant.brain_api.Dust3rInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('covariant.brain_api.Dust3rInferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Dust3rInferenceService(object):
    """Service for running Dust3r depth inference
    """

    @staticmethod
    def PredictDepth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/covariant.brain_api.Dust3rInferenceService/PredictDepth',
            dust3r_dot_proto_dot_inference_dot_predict__depth__with__dust3r__pb2.PredictDust3rDepthRequest.SerializeToString,
            dust3r_dot_proto_dot_inference_dot_predict__depth__with__dust3r__pb2.PredictDust3rDepthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
