# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dust3r/proto/inference/predict_depth_with_dust3r.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'dust3r/proto/inference/predict_depth_with_dust3r.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dust3r.proto.common import camera_pb2 as dust3r_dot_proto_dot_common_dot_camera__pb2
from dust3r.proto.common import calibration_pb2 as dust3r_dot_proto_dot_common_dot_calibration__pb2
from dust3r.proto.common import ids_pb2 as dust3r_dot_proto_dot_common_dot_ids__pb2
from dust3r.proto.common import image_pb2 as dust3r_dot_proto_dot_common_dot_image__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6dust3r/proto/inference/predict_depth_with_dust3r.proto\x12\x13\x63ovariant.brain_api\x1a dust3r/proto/common/camera.proto\x1a%dust3r/proto/common/calibration.proto\x1a\x1d\x64ust3r/proto/common/ids.proto\x1a\x1f\x64ust3r/proto/common/image.proto\"\xdc\x01\n\x19PredictDust3rDepthRequest\x12\x39\n\x0f\x63\x61ptured_images\x18\x01 \x03(\x0b\x32 .covariant.brain_api.CameraImage\x12:\n\x13reference_camera_id\x18\x02 \x01(\x0b\x32\x1d.covariant.brain_api.CameraID\x12H\n\x0b\x63\x61mera_info\x18\x03 \x01(\x0b\x32\x33.covariant.brain_api.CameraRigCalibrationParameters\"\x7f\n\x1aPredictDust3rDepthResponse\x12-\n\tdepth_map\x18\x01 \x01(\x0b\x32\x1a.covariant.brain_api.Image\x12\x32\n\x0e\x63onfidence_map\x18\x02 \x01(\x0b\x32\x1a.covariant.brain_api.Image2\x89\x01\n\x16\x44ust3rInferenceService\x12o\n\x0cPredictDepth\x12..covariant.brain_api.PredictDust3rDepthRequest\x1a/.covariant.brain_api.PredictDust3rDepthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dust3r.proto.inference.predict_depth_with_dust3r_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTDUST3RDEPTHREQUEST']._serialized_start=217
  _globals['_PREDICTDUST3RDEPTHREQUEST']._serialized_end=437
  _globals['_PREDICTDUST3RDEPTHRESPONSE']._serialized_start=439
  _globals['_PREDICTDUST3RDEPTHRESPONSE']._serialized_end=566
  _globals['_DUST3RINFERENCESERVICE']._serialized_start=569
  _globals['_DUST3RINFERENCESERVICE']._serialized_end=706
# @@protoc_insertion_point(module_scope)
